# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29f9d6e29253abf9a61d445c9e8c48de6742e673e45d4d7197f4b72d53695cce89252a740f0d659e4200e9fe6711380b57a721ec1d0325db3cafa41e45c244b6

test:
  secret_key_base: e9e3ff9c115adbe238a6fd22ccd9861eeaf9187232719ec81ecc3876bb7dd43e70e720b4f37dd155f08016cdbe7cce2f8799c3efb901e737c0c2e5f21623105b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
